server:
  port: 8080
spring:
  mvc:
     static-path-pattern: /**
     # 静态资源访问　默认值为 classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  thymeleaf:
    prefix: classpath:/templates/
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
      name: test
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/museum
      username: root
      password: root
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.muzi.museum.bean
  configuration:
    map-underscore-to-camel-case: true

msg-config:
  swagger-open: true

thymeleaf:
  cache: false

#配置日志
logging: #配置日志文件路径
  path: log
  level:
        xatu.zsl: debug #不同目录下的日志可配置不同级别
        org.springfromework.web: info
        org.hibernate: error



